import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import React from "react";
import Markdown from "react-markdown";
const inter = Inter({ subsets: ["latin"] });

export default function Blog(props: any) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Markdown>{props.children}</Markdown>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const children = require("../blogposts/test.md").default;
  return {
    props: {
      children,
    },
  };
}
