import Head from "next/head";
import styles from "../styles/Home.module.css";
import { TextField } from "@mui/material";
import React, { useState } from "react";
import axios from "axios";

export default function Contact() {
  const [name, setName] = useState("");
  const [message, setMessage] = useState("");
  const [email, setEmail] = useState("");
  const [subject, setSubject] = useState("");
  const [sent, setSent] = useState(false);
  const [buttonText, setButtonText] = useState("Send Message");
  const [emailError, setEmailError] = useState(false);

  const resetForm = () => {
    setName("");
    setMessage("");
    setEmail("");
    setSubject("");
    setButtonText("Message Sent");

    setTimeout(() => {
      setSent(false);
    }, 3000);
  };

  const handleChangeEmail = (e: any) => {
    if (
      !e.target.value.match(
        /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
      )
    ) {
      setEmail(e.target.value);
      setEmailError(true);
      if (email === "") {
        setEmailError(false);
      }
    } else {
      setEmail(e.target.value);
      setEmailError(false);
    }
  };

  const formSubmit = async (e: any) => {
    e.preventDefault();
    setButtonText("...sending");

    let data = {
      name,
      email,
      message,
      subject,
    };

    try {
      const res = await axios.post("http://localhost:3000/api/SendEmail", data);
      console.log(res);
      setSent(true);
      resetForm();
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Josh Gilley</title>
        <meta name="description" content="Generated by create next app" />
        <meta content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no' name='viewport' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <form className="contact-form" onSubmit={(e) => formSubmit(e)}>
            <TextField
              id="standard-multiline-flexible"
              label="Message"
              placeholder="Enter Message"
              variant="outlined"
              multiline
              //   rowsMax={4}
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              required
              type="text"
            />
            <br />
            <br />
            <br />

            <TextField
              id="outlined-basic"
              placeholder="Enter your name"
              label="Name"
              variant="outlined"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              type="text"
            />
            <br />
            <br />
            <br />

            <TextField
              id="outlined-basic"
              label="Email"
              placeholder="Enter email address"
              variant="outlined"
              value={email}
              onChange={(e) => handleChangeEmail(e)}
              error={emailError}
              required
              type="email"
            />
            <br />
            <br />
            <br />
            <TextField
              id="outlined-basic"
              placeholder="Enter Subject"
              label="Subject"
              variant="outlined"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              required
            />
            <br />
            <br />
            <br />
            <div className="button--container">
              <button type="submit" className="button button-primary">
                {buttonText}
              </button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
