import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box } from "@mui/material";
import TypingEffect from "../components/common/TypingEffect";

export default function Home() {
  const myNameIs = "I'm Josh";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.myName}>
            <p className={styles.myNameIs}>{myNameIs}</p>
          </div>
        </div>
        <div className={styles.typingEffect}>
          <Box>
            <TypingEffect
              staticText="I am a"
              text={["software engineer", "cloud developer"]}
            />
          </Box>
        </div>
      </main>
    </>
  );
}
