import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box } from "@mui/material";
import TypingEffect from "../components/common/TypingEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Josh Gilley</title>
        <meta name="description" content="Generated by create next app" />
        <meta content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no' name='viewport' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.myName}>
            <p className={styles.myNameIs}>{"I'm Josh"}</p>
          </div>
        </div>
        <div className={styles.typingEffect}>
          <Box>
            <TypingEffect
              staticText="I am a"
              text={["software engineer", "cloud developer"]}
            />
          </Box>
        </div>
      </main>
    </>
  );
}
