import matter from "gray-matter";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import path from "path";
import React from "react";
import fs from "fs";
import { Post } from "../types/Post.interface";
import CardComponent from "../components/common/CardComponent";
import style from "../styles/Blog.module.css";

export default function Blog({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Josh Gilley</title>
        <meta name="description" content="Generated by create next app" />
        <meta content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no' name='viewport' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.wrapper}>
        {posts.map((post: Post, index: number) => {
          return <div key={`card_${index}`} className={style.cards}><CardComponent key={index} post={post} /></div>;
        })}
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const articlesDirectory = path.join("project_articles");
  const files = fs.readdirSync(articlesDirectory);

  const projectPosts = files.map((fileName: string) => {
    const slug = fileName.replace(".mdx", "");
    const article = fs.readFileSync(path.join("project_articles", fileName));
    const { data: metaData } = matter(article);
    return { slug, metaData };
  });

  return { props: { posts: projectPosts } };
};
